public class DemoApex {

    public static void method1(){
        
        Boolean isActive = true;
        System.debug('Value of isActive '+ isActive);
    }
    public static void method2(){
     	String fname = 'Abhishek', lname = 'Bhalerao'; 
        System.debug('Name =' + fname + ' ' + lname);
    }
    public static void method3(){
        ID accId = '00100000009R2XWPPO';
        System.debug('Id =' +accId);
        
    }
}